name: Linter

on:
  pull_request:
    paths-ignore:
      - '.github/**'

permissions:
  contents: read
  packages: read
  statuses: write # To report GitHub Actions status checks
  
jobs:
  build:
    name: 'âœ¨ Linter'
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.11.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          
      - name: Lint Code Base with Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          DEFAULT_BRANCH: origin/main
          VALIDATE_ALL_CODEBASE: false # tells the linter to only check files that have been modified in the current pull request
          VALIDATE_GO: true
          VALIDATE_GOFMT: true
          VALIDATE_GOCYCLO: true
          VALIDATE_GOVET: true
          VALIDATE_GOLANGCI_LINT: true
          VALIDATE_CPD: false # Disable CPD (Copy Paste Detection) for all languages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # To report GitHub Actions status checks
          MARKDOWN_CONFIG_FILE: .markdown-lint.yml
          FILTER_REGEX_EXCLUDE: |
            .*\.md$|                # Exclude all markdown files
            .*test/.*|              # Exclude all files in any test directory
            .*_test\.go$|           # Exclude Go test files (e.g., *_test.go)
            .*\.json$               # Exclude all JSON files
