name: Save Artifacts

on:
  # This file is reused, and called from other workflows
  workflow_call:

permissions:
  contents: read

jobs:
  save-artifacts:
    runs-on: ubuntu-24.04-arm
    steps:
      - shell: bash
        run: |
          mkdir -p wr_actions
          echo ${{ github.repository_owner }} > wr_actions/ghowner.txt
          echo ${{ github.event.repository.name }} > wr_actions/ghrepo.txt
          echo ${{ github.event.pull_request.number }} > wr_actions/prnumber.txt
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: artifact
          path: wr_actions