name: generate terraform docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**/*'
      - 'scripts/**/*'
  workflow_dispatch:

permissions:
  contents: write  # Required to update documentation in the repo
  pull-requests: write
  
jobs:
  tf-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@v4.2.2
      with:
        ref: main
    # Creates provider documentation for registry.terraform.io
    - name: Render terraform docs for microsoft365_graph
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        config-file: .terraform-docs.yml
        find-dir: examples/
        recursive: true
        indention: 3
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
        git-push-user-name: "github-actions[bot]"
        git-push-user-email: "github-actions[bot]@users.noreply.github.com"